services:
  mongo:
    image: mongo:7
    container_name: wealthx-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: wealthx-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client/vite-project
    container_name: wealthx-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data: