apiVersion: v1
kind: Service

metadata:
  name: wealthx-backend-service

spec:
  selector:
    app: wealthx-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP