apiVersion: v1
kind: Secret

metadata:
  name: wealthx-backend-secret

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://pranavbhat620_db_user:F5torV5LtkBdpTs6@cluster0.rix9hu5.mongodb.net/wealthx?retryWrites=true&w=majority"
  JWT_SECRET: "your_super_secret_jwt_key_wealthx_2026"